# Generated by Django 5.1.4 on 2026-06-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vp', models.CharField(max_length=100)),
                ('farmer_name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('village', models.CharField(max_length=100)),
                ('plot_number', models.CharField(max_length=50)),
                ('area', models.FloatField()),
                ('variety', models.CharField(max_length=100)),
                ('planting_date', models.DateField()),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
