# Generated by Django 5.1.4 on 2026-06-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_officer_role_delete_login_officer_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='user_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
