# Generated by Django 5.1.4 on 2026-06-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_officer_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='permissions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
