# Generated by Django 5.1.4 on 2026-06-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_officer_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='user_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
