# Generated by Django 5.1.4 on 2026-06-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_officer_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='password',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='officer',
            name='user_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
