# Generated by Django 5.1.4 on 2026-06-01 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_officer_password_alter_officer_user_id'),
    ]

    operations = [
    ]
