# Generated by Django 5.1.4 on 2026-06-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20260601_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='permissions',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
