# Generated by Django 5.1.4 on 2026-06-02 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('village_name', models.CharField(max_length=100)),
                ('status', models.CharField(default='active', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='myapp.section')),
            ],
        ),
    ]
