# Generated by Django 5.1.4 on 2026-06-02 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_farmer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('crop_type', models.CharField(max_length=100)),
                ('variety_name', models.CharField(max_length=150)),
                ('season', models.CharField(max_length=50)),
            ],
        ),
    ]
