# Generated by Django 5.1.4 on 2026-06-02 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_season_alter_variety_season'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION update_officer_user_id()
                RETURNS trigger AS $$
                BEGIN
                    IF NEW.name <> OLD.name THEN
                        UPDATE myapp_officer 
                        SET user_id = REPLACE(NEW.name, ' ', '')
                        WHERE role_id = NEW.id;
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                DROP TRIGGER IF EXISTS trg_update_officer_user_id ON myapp_role;

                CREATE TRIGGER trg_update_officer_user_id
                AFTER UPDATE ON myapp_role
                FOR EACH ROW
                EXECUTE FUNCTION update_officer_user_id();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS trg_update_officer_user_id ON myapp_role;
                DROP FUNCTION IF EXISTS update_officer_user_id();
            """
        )
    ]
