# Generated by Django 5.1.4 on 2026-06-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_role_officer_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='role_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION update_officer_user_id()
                RETURNS trigger AS $$
                BEGIN
                    IF NEW.name <> OLD.name THEN
                        UPDATE myapp_officer 
                        SET user_id = REPLACE(NEW.name, ' ', ''),
                            role_name = NEW.name
                        WHERE role_id = NEW.id;
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;
            """,
            reverse_sql="""
                CREATE OR REPLACE FUNCTION update_officer_user_id()
                RETURNS trigger AS $$
                BEGIN
                    IF NEW.name <> OLD.name THEN
                        UPDATE myapp_officer 
                        SET user_id = REPLACE(NEW.name, ' ', '')
                        WHERE role_id = NEW.id;
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;
            """
        )
    ]
