# Generated by Django 5.1.4 on 2026-06-02 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_officer_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variety',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.section'),
        ),
        migrations.DeleteModel(
            name='Season',
        ),
    ]
