# Generated by Django 5.1.4 on 2026-06-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_variety_season_delete_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='village',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='village',
            name='taluk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
