# Generated by Django 5.1.4 on 2026-06-03 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_factory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('factory_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='myapp.factory')),
            ],
        ),
    ]
