# Generated by Django 5.1.4 on 2026-06-03 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.division'),
        ),
    ]
