# Generated by Django 5.1.4 on 2026-06-03 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_section_division'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='division',
            table='division',
        ),
        migrations.AlterModelTable(
            name='factory',
            table='factory',
        ),
        migrations.AlterModelTable(
            name='farmer',
            table='farmer',
        ),
        migrations.AlterModelTable(
            name='group',
            table='group',
        ),
        migrations.AlterModelTable(
            name='officer',
            table='officer',
        ),
        migrations.AlterModelTable(
            name='role',
            table='role',
        ),
        migrations.AlterModelTable(
            name='section',
            table='section',
        ),
        migrations.AlterModelTable(
            name='variety',
            table='variety',
        ),
        migrations.AlterModelTable(
            name='village',
            table='village',
        ),
    ]
