# Generated by Django 5.1.4 on 2026-06-03 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_division_table_alter_factory_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='group',
            table='group_master',
        ),
    ]
