# Generated by Django 5.1.4 on 2026-06-03 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_alter_group_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.group'),
        ),
    ]
