# Generated by Django 5.1.4 on 2026-06-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_officer_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officer',
            name='division',
        ),
        migrations.AddField(
            model_name='officer',
            name='divisions',
            field=models.ManyToManyField(blank=True, to='myapp.division'),
        ),
        migrations.AddField(
            model_name='officer',
            name='factories',
            field=models.ManyToManyField(blank=True, to='myapp.factory'),
        ),
        migrations.AddField(
            model_name='officer',
            name='sections',
            field=models.ManyToManyField(blank=True, to='myapp.section'),
        ),
    ]
