# Generated by Django 5.1.4 on 2026-06-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_remove_officer_division_officer_divisions_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='officer',
                    name='divisions',
                ),
                migrations.RemoveField(
                    model_name='officer',
                    name='factories',
                ),
                migrations.RemoveField(
                    model_name='officer',
                    name='sections',
                ),
            ]
        ),
        migrations.AddField(
            model_name='officer',
            name='division_ids',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='division_names',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='factory_ids',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='factory_names',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='section_ids',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='section_names',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
