# Generated by Django 5.1.4 on 2026-06-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_remove_officer_divisions_remove_officer_factories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='division_ids',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='officer',
            name='division_names',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='officer',
            name='factory_ids',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='officer',
            name='factory_names',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='officer',
            name='section_ids',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='officer',
            name='section_names',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
