# Generated by Django 5.1.4 on 2026-06-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_alter_officer_division_ids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='division',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
