# Generated by Django 5.1.4 on 2026-06-09 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_village_division'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkAssign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_assign_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('division', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_assigns', to='myapp.officer')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_assigns', to='myapp.section')),
                ('village', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_assigns', to='myapp.village')),
            ],
            options={
                'db_table': 'work_assign',
            },
        ),
    ]
