# Generated by Django 5.1.4 on 2026-06-09 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_workassign_device_id_workassign_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variety',
            name='crop_type',
        ),
        migrations.RemoveField(
            model_name='variety',
            name='season',
        ),
    ]
