# Generated by Django 5.1.4 on 2026-06-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_remove_variety_crop_type_remove_variety_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('crop_name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'crop',
            },
        ),
    ]
