# Generated by Django 5.1.4 on 2026-06-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_crop'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='group_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
