# Generated by Django 5.1.4 on 2026-06-09 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_officer_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='variety',
            name='crop_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='varieties', to='myapp.crop'),
        ),
    ]
