# Generated by Django 5.1.4 on 2026-06-09 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_variety_crop_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.group'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='group_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
