# Generated by Django 5.1.4 on 2026-06-09 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_farmer_group_farmer_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.factory'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='factory_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
