# Generated by Django 5.1.4 on 2026-06-09 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_farmer_factory_farmer_factory_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('division_name', models.CharField(blank=True, max_length=100, null=True)),
                ('section_name', models.CharField(blank=True, max_length=100, null=True)),
                ('village_name', models.CharField(blank=True, max_length=100, null=True)),
                ('planting_date', models.DateField(blank=True, null=True)),
                ('area_acre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_mapped', models.BooleanField(default=False)),
                ('land_image', models.ImageField(blank=True, null=True, upload_to='plot_images/')),
                ('crop_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.crop')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.division')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='myapp.farmer')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.section')),
                ('variety', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.variety')),
                ('village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.village')),
            ],
            options={
                'db_table': 'plot',
            },
        ),
    ]
