# Generated by Django 5.1.4 on 2026-06-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_plot'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plot',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plot',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
