# Generated by Django 5.1.4 on 2026-06-09 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_plot_device_id_plot_latitude_plot_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.factory'),
        ),
        migrations.AddField(
            model_name='plot',
            name='factory_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plot',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.group'),
        ),
        migrations.AddField(
            model_name='plot',
            name='group_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
