# Generated by Django 5.1.4 on 2026-06-09 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_plot_factory_plot_factory_name_plot_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_plots', to='myapp.officer'),
        ),
    ]
