# Generated by Django 5.1.4 on 2026-06-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_plot_officer'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='land_image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
