# Generated by Django 5.1.4 on 2026-06-10 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_plot_land_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plot',
            name='land_image',
        ),
        migrations.RemoveField(
            model_name='plot',
            name='land_image_url',
        ),
    ]
