# Generated by Django 5.1.4 on 2026-06-10 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_remove_plot_land_image_remove_plot_land_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_code', models.CharField(blank=True, max_length=50, null=True)),
                ('division', models.CharField(blank=True, max_length=100, null=True)),
                ('section', models.CharField(blank=True, max_length=100, null=True)),
                ('village', models.CharField(blank=True, max_length=100, null=True)),
                ('group_name', models.CharField(blank=True, max_length=100, null=True)),
                ('factory_name', models.CharField(blank=True, max_length=100, null=True)),
                ('boundary', models.JSONField(blank=True, null=True)),
                ('img1', models.ImageField(blank=True, null=True, upload_to='field_images/')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='field_images/')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='field_images/')),
                ('officer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('factory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.factory')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_mappings', to='myapp.farmer')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.group')),
                ('officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.officer')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_mappings', to='myapp.plot')),
            ],
            options={
                'db_table': 'field_mapping',
            },
        ),
    ]
