# Generated by Django 5.1.4 on 2026-06-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0046_fieldmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('soil_name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'soil_type',
            },
        ),
    ]
