# Generated by Django 5.1.4 on 2026-06-10 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0047_soiltype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plot',
            name='is_mapped',
        ),
        migrations.AddField(
            model_name='plot',
            name='soil_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.soiltype'),
        ),
        migrations.AddField(
            model_name='plot',
            name='status',
            field=models.CharField(default='Not Mapped', max_length=50),
        ),
    ]
