# Generated by Django 5.1.4 on 2026-06-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0049_plot_crushing_season_plot_gps_area_plot_harvest_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='boundary_image',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
