# Generated by Django 5.1.4 on 2026-06-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0050_plot_boundary_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='center_lt_ln',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plot',
            name='latitude',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plot',
            name='longitude',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
