# Generated by Django 5.1.4 on 2026-06-13 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0051_plot_center_lt_ln_alter_plot_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoutingLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=100, null=True)),
                ('plant_height', models.CharField(blank=True, max_length=100, null=True)),
                ('growth_stage', models.CharField(blank=True, max_length=100, null=True)),
                ('pest_presence', models.BooleanField(default=False)),
                ('pest_type', models.CharField(blank=True, max_length=150, null=True)),
                ('pest_severity', models.CharField(blank=True, max_length=50, null=True)),
                ('disease_presence', models.BooleanField(default=False)),
                ('disease_type', models.CharField(blank=True, max_length=150, null=True)),
                ('disease_photo', models.ImageField(blank=True, null=True, upload_to='scouting_photos/')),
                ('water_sufficiency', models.CharField(blank=True, max_length=100, null=True)),
                ('water_stress_symptoms', models.BooleanField(default=False)),
                ('nutrient_deficiency', models.BooleanField(default=False)),
                ('deficiency_symptoms', models.CharField(blank=True, max_length=200, null=True)),
                ('fertilizer_recommendation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.division')),
                ('factory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.factory')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.group')),
                ('officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.officer')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scouting_logs', to='myapp.plot')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.section')),
                ('village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.village')),
            ],
            options={
                'db_table': 'scouting_log',
            },
        ),
    ]
