# Generated by Django 5.1.4 on 2026-06-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0052_scoutinglog'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='boundaries',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
