# Generated by Django 5.1.4 on 2026-06-18 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0053_plot_boundaries'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('survey_stage', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('survey_month', models.CharField(blank=True, max_length=50, null=True)),
                ('number_of_days', models.IntegerField(default=0)),
                ('allocated_dates', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('completion_percentage', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys', to='myapp.officer')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='myapp.plot')),
            ],
            options={
                'db_table': 'survey',
            },
        ),
    ]
