# Generated by Django 5.1.4 on 2026-06-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0054_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='disease_incidence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='field_photo1',
            field=models.ImageField(blank=True, null=True, upload_to='survey_photos/'),
        ),
        migrations.AddField(
            model_name='survey',
            name='field_photo2',
            field=models.ImageField(blank=True, null=True, upload_to='survey_photos/'),
        ),
        migrations.AddField(
            model_name='survey',
            name='field_photo3',
            field=models.ImageField(blank=True, null=True, upload_to='survey_photos/'),
        ),
        migrations.AddField(
            model_name='survey',
            name='irrigation_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='nutrition_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='pest_incidence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='tillering_vigour',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='weed_infestation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
