# Generated by Django 5.1.4 on 2026-06-21 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0055_survey_disease_incidence_survey_field_photo1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='disease_incidence',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='field_photo1',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='field_photo2',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='field_photo3',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='irrigation_status',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='nutrition_status',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='pest_incidence',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='tillering_vigour',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='weed_infestation',
        ),
        migrations.CreateModel(
            name='SurveyResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weed_infestation', models.CharField(blank=True, max_length=100, null=True)),
                ('tillering_vigour', models.CharField(blank=True, max_length=100, null=True)),
                ('pest_incidence', models.CharField(blank=True, max_length=100, null=True)),
                ('disease_incidence', models.CharField(blank=True, max_length=100, null=True)),
                ('irrigation_status', models.CharField(blank=True, max_length=100, null=True)),
                ('nutrition_status', models.CharField(blank=True, max_length=100, null=True)),
                ('field_photo1', models.ImageField(blank=True, null=True, upload_to='survey_photos/')),
                ('field_photo2', models.ImageField(blank=True, null=True, upload_to='survey_photos/')),
                ('field_photo3', models.ImageField(blank=True, null=True, upload_to='survey_photos/')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='myapp.survey')),
            ],
            options={
                'db_table': 'survey_result',
            },
        ),
    ]
