# Generated by Django 5.1.4 on 2026-06-21 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0056_remove_survey_disease_incidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresult',
            name='survey_date',
            field=models.DateField(blank=True, help_text='Date when this survey result was taken', null=True),
        ),
        migrations.AlterField(
            model_name='surveyresult',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='myapp.survey'),
        ),
    ]
