# Generated by Django 5.1.4 on 2026-06-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0057_surveyresult_survey_date_alter_surveyresult_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresult',
            name='field_photo1',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='surveyresult',
            name='field_photo2',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='surveyresult',
            name='field_photo3',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
