# Generated by Django 5.1.4 on 2026-06-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0058_alter_surveyresult_field_photo1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresult',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
