# Generated by Django 5.1.4 on 2026-06-21 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0059_surveyresult_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='completion_percentage',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='status',
        ),
    ]
