# Generated by Django 5.1.4 on 2026-06-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0060_remove_survey_completion_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresult',
            name='completion_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
