# Generated by Django 5.1.4 on 2026-06-21 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0061_surveyresult_completion_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyresult',
            old_name='status',
            new_name='survey_status',
        ),
    ]
