# Generated by Django 5.1.4 on 2026-06-24 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0062_rename_status_surveyresult_survey_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='NDVIRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recorded', models.DateField()),
                ('ndvi_value', models.DecimalField(decimal_places=4, max_digits=5)),
                ('cloud_cover', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('health_status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ndvi_records', to='myapp.plot')),
            ],
            options={
                'db_table': 'ndvi_record',
                'ordering': ['-date_recorded'],
            },
        ),
        migrations.CreateModel(
            name='Scout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scout_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('ndvi_value', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('alert_reason', models.TextField()),
                ('priority', models.CharField(default='Medium', max_length=20)),
                ('status', models.CharField(default='Pending Assignment', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scouts', to='myapp.plot')),
            ],
            options={
                'db_table': 'scout',
            },
        ),
        migrations.CreateModel(
            name='ScoutAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_scouts', to='myapp.officer')),
                ('scout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='myapp.scout')),
            ],
            options={
                'db_table': 'scout_assignment',
            },
        ),
        migrations.CreateModel(
            name='ScoutSurveyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_photo1', models.ImageField(blank=True, null=True, upload_to='scout_photos/')),
                ('field_photo2', models.ImageField(blank=True, null=True, upload_to='scout_photos/')),
                ('observations', models.TextField(blank=True, null=True)),
                ('pest_details', models.TextField(blank=True, null=True)),
                ('disease_details', models.TextField(blank=True, null=True)),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scout_reports', to='myapp.officer')),
                ('scout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey_report', to='myapp.scout')),
            ],
            options={
                'db_table': 'scout_survey_report',
            },
        ),
    ]
