# Generated by Django 5.1.4 on 2026-07-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0063_ndvirecord_scout_scoutassignment_scoutsurveyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='ndvirecord',
            name='attn_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='ndvirecord',
            name='crop_age_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ndvirecord',
            name='good_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='ndvirecord',
            name='mod_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='ndvirecord',
            name='ndvi_max',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='ndvirecord',
            name='ndvi_mean',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='ndvirecord',
            name='ndvi_min',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='ndvirecord',
            name='px_attn',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ndvirecord',
            name='px_good',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ndvirecord',
            name='px_mod',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ndvirecord',
            name='px_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ndvirecord',
            name='stage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ndvirecord',
            name='thr_max',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='ndvirecord',
            name='thr_min',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
    ]
