# Generated by Django 5.1.4 on 2026-07-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0064_ndvirecord_attn_percent_ndvirecord_crop_age_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ndvirecord',
            name='division_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ndvirecord',
            name='factory_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ndvirecord',
            name='farmer_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ndvirecord',
            name='group_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ndvirecord',
            name='plot_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ndvirecord',
            name='section_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ndvirecord',
            name='village_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
