# Generated by Django 5.1.4 on 2026-07-04 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0065_ndvirecord_division_name_ndvirecord_factory_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ndvirecord',
            name='division_name',
        ),
        migrations.RemoveField(
            model_name='ndvirecord',
            name='factory_name',
        ),
        migrations.RemoveField(
            model_name='ndvirecord',
            name='farmer_name',
        ),
        migrations.RemoveField(
            model_name='ndvirecord',
            name='group_name',
        ),
        migrations.RemoveField(
            model_name='ndvirecord',
            name='plot_name',
        ),
        migrations.RemoveField(
            model_name='ndvirecord',
            name='section_name',
        ),
        migrations.RemoveField(
            model_name='ndvirecord',
            name='village_name',
        ),
    ]
