# Generated by Django 5.1.4 on 2026-07-05 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0066_remove_ndvirecord_division_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoutResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_scout_id', models.CharField(blank=True, max_length=50, null=True)),
                ('farmer_name', models.CharField(blank=True, max_length=150, null=True)),
                ('plot_id', models.CharField(blank=True, max_length=50, null=True)),
                ('recommendation_adopted', models.BooleanField(default=False)),
                ('current_problem_status', models.CharField(blank=True, max_length=255, null=True)),
                ('current_crop_status', models.CharField(blank=True, max_length=255, null=True)),
                ('seek_expert_help', models.BooleanField(default=False)),
                ('field_photos', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'scout_result',
            },
        ),
    ]
