# Generated by Django 5.1.4 on 2026-07-24 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0067_scoutresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.factory'),
        ),
        migrations.AddField(
            model_name='survey',
            name='factory_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.group'),
        ),
        migrations.AddField(
            model_name='survey',
            name='group_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='plot_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
