# Generated by Django 5.1.4 on 2026-08-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0068_survey_factory_survey_factory_name_survey_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoutresult',
            name='disease',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scoutresult',
            name='farmer_neg',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scoutresult',
            name='nutrition',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scoutresult',
            name='pest',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scoutresult',
            name='plant_population',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scoutresult',
            name='soil_related',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scoutresult',
            name='water',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scoutresult',
            name='weed',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
