# Generated by Django 5.1.4 on 2026-08-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0069_scoutresult_disease_scoutresult_farmer_neg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoutresult',
            name='next_follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
